const defaultParams = {};

export const createFilterSlice = (set) => ({
  params: { ...defaultParams },
  setPage: (page) => set((state) => ({ params: { ...state.params, page } })),
  cities: {},
  setCities: (cities) => set({ cities }),
  employment: {},
  setEmployment: (employment) => set({ employment }),
  filter: {},
  setFilter: (filter) => set({ filter }),
  publishDate: { 'allTime': 'За все время'},
  setPublishDate: (publishDate) => set({ publishDate }),
  experience: { 'doesNotMatter': 'Не имеет значения'},
  setExperience: (experience) => set({ experience }),
  workSchedule: {},
  setWorkSchedule: (workSchedule) => set({ workSchedule }),
  technologyTags: {},
  setTechnologyTags: (technologyTags) => set({ technologyTags }),
  graduation: {},
  setGraduation: (graduation) => set({ graduation }),
  incomeLevel: { 'doesNotMatter': 'Не имеет значения' },
  setIncomeLevel: (incomeLevel) => set({ incomeLevel }),
  underworking: {},
  setUnderworking: (underworking) => set({ underworking }),
  moreFilters: {},
  setMoreFilters: (moreFilters) => set({ moreFilters }),
});